version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PGPASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - botnet
    restart: on-failure
    volumes:
      - .redis:/var/lib/redis
    ports:
      - 6379:6379

  bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db
      - redis


networks:
  botnet:
    driver: bridge