name: Build

on:
  push:
    branches:
    - master
    - features/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create env file
      run: |
        touch .env
        echo POSTGRES_USER=postgres >> .env
        echo POSTGRES_PASSWORD=testpassword >> .env
        echo POSTGRES_DB=localhost >> .env
        cat .env
    - name: Build containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down