name: Build and deploy

on:
  push:
    branches:
    - master
    - features/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create env file
      run: |
        touch .env
        echo POSTGRES_USER=postgres >> .env
        echo POSTGRES_PASSWORD=testpassword >> .env
        echo POSTGRES_DB=localhost >> .env
        cat .env

    - name: Build containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "~/schedule_bot"

    - name: Build and restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: docker-compose build && docker-compose restart && docker image rm $(docker image ls -f dangling=true -q)